[workspace]
exclude = ["tests/cargo-index-transit"]

[package]
name = "cargo-fix-minimal-versions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.77.0"
clap = "4.5.1"
semver = "1.0.22"
